### ISSUE TITLE
Split "Auto" layout not woking on Galaxy Z Fold

### ISSUE THREAD

**Issue by starcraft66** [K1rakishou/KurobaExLite#1]
Decided to give this app a shot after our previous discussion  [here](https://github.com/K1rakishou/Kuroba-Experimental/issues/839). It seems that despite my phone being wide enough, selecting the "auto" layout produces an error with conflicting information about my phone not being wide enough but being wide enough at the same time.

![Screenshot_20221105_114714_KurobaExLite.jpg](https://user-images.githubusercontent.com/1858154/200128565-e42e46fc-609d-475d-a8ba-5955f15b8135.jpg)

**Comment by K1rakishou** [comment]
Yeah, those numbers are displayed in an incorrect order.
Ok, I have updated the check to not use hardcoded values so now it should work.
Fixed in https://github.com/K1rakishou/KurobaExLite/commit/a0107f2635fb3a3aa5b017ac68c8b5e47a60daab
