### ISSUE TITLE
Application does not reserve apace for Android 12L taskbar

### ISSUE THREAD

**Issue by starcraft66** [K1rakishou/KurobaExLite#2]
As seen in the screenshot I posted in #1, the app does not seem to reserve space at the bottom of the display and the taskbar and navigation bar just overlap over whatever is being displayed at the bottom of the interface.

![image](https://user-images.githubusercontent.com/10332458/200155414-6fcf0457-a81b-4226-9565-9be12275ac8a.png)

**Comment by K1rakishou** [comment]
Now this is weird because it works for me in the emulator.

![image](https://user-images.githubusercontent.com/10332458/200155401-f60b9c3b-abf9-42ee-9497-339c2309c877.png)

**Comment by K1rakishou** [comment]
Ok, I think I managed to reproduce and fix this bug.
https://github.com/K1rakishou/KurobaExLite/commit/d2af9f90b6dd31ee67c3280a76d42bd4df44fd1b
