### ISSUE TITLE
App isn't responding in split mode 

### ISSUE THREAD

**Issue by clutzygamers** [K1rakishou/KurobaExLite#3]
Can't open anything on the 1.08 update when in split mode, for example tapping "select a catalog" does nothing. It works in phone mode though.

**Comment by starcraft66** [comment]
I have the same issue with the latest release on the galaxy z fold. Everything worked until I opened the app on the cover screen and then unfolded to switch to the inner display. The app changed to the split view but I was stuck in a bookmarks menu.

https://user-images.githubusercontent.com/1858154/201533318-aafe6903-6a60-4d76-b521-964843b98a6b.mp4

**Comment by K1rakishou** [comment]
Fixed in https://github.com/K1rakishou/KurobaExLite/commit/16a7319f7169a13a92f8f7a445906ad6c6e46213
