### ISSUE TITLE
Add a setting to display mini drawer on foldable phones.

### ISSUE THREAD

**Issue by clutzygamers** [K1rakishou/KurobaExLite#4]
The below part is missing. 

![200155401-f60b9c3b-abf9-42ee-9497-339c2309c877](https://user-images.githubusercontent.com/84054190/202115806-6006635d-c821-4943-ba69-471322b272c7.png)

**Comment by K1rakishou** [comment]
Yes it only shows up on tablets. Foldable phones are not considered tablets. It was done like that because I'm not sure how much of horizontal space there is on foldable phones and whether everything would fit. Maybe I could add a setting to force show it anyway.

**Comment by clutzygamers** [comment]
>Maybe I could add a setting to force show it anyway.

Yes please, or maybe just keep both the board and threads together like the regular slide mode if there's still not enough space.

**Comment by K1rakishou** [comment]
This was fixed. The minidrawer will now be displayed on foldable phones too.
